language: ruby
rvm:
- 2.3.5
deploy:
  api_key:
    secure: fnwIdFNV7EyUSeSDLM2xrwwTWRfMuTONFkdxMVGm36QFavP6tAzqn0d1qIeups9ixgz0eZqOR6g4Mkxt6BVe6lolA4f+K/Cq0X414ualcCe5SJ7hg2pudnBhWUG0M16y0CMfLeIHozEpCgEuW/sXLxf9aySeJOvZzyx5Ad/L0HWQCd5C+x5oL44LNaciV/63LodZIPR+KtBaC1TOP6oaMkwqnsAWV5Evss2K5Yf8YVDcVfVlUOZgzBkL9WvfLvOn3YsY7Rvmthtj9SJCNOi8amyQj0yqMSZB9nbLjslWB9YbSyNcRben2dtRUJSXIseuyjoiLa9f3zmzNCkL8nsQj6XXxgbXSYoX2TMtuwbVI/Lu5Aro9i4EIzgwbzksoFrZybN0otLvbti0+lwcYD/EW+GrdW5Ilmj9HKwFVthdY5jTYbi7mJSnMiQLlrP99+BtX4BXxDvWYmq4Z+td8dEoY91V4bs0wn8pHQQ6eTytfoYGtUquw3OJ/g2r5BuCsVcLPPpfZz3xYyAj6jEgZ75+6nSM89XGdXL6OcOLeholFSOLrFEJ9DFN4yD9+2Mw6cK6+7c9TSuHK3bIzQn7DsEcGYzwXDgBp3KnpaCbDwfycR/wdGqo5Br3ogBeNleuuxA/x1mLsBlEzdazy3LZ5KKHuKguVUceleXsNn+rNYwH9YM=
 provider: heroku
 app: weshmopi